name: Deploy Portfolio

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Debug secret
        run: echo "Length of GH_PAT is ${#GH_PAT}"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Build and Deploy
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: ./scripts/deploy.sh
